### ISSUE TITLE
Intel MKL ERROR: CPU 0 is not supported.

### ISSUE THREAD

**Issue by DemoorBug** [NyaomiDEV/AMDFriend#4]
System: Big Sur 11.6
CPU: AMD 3600
Language: Python

I'm getting errors with matplotlib, I don't know if this project can be solved? Please help me
<img width="861" alt="2022-11-03 2 13 29" src="https://user-images.githubusercontent.com/18387615/199657674-f4405244-9f71-4c3c-a9bc-2d2c72ba7d84.png">

**Comment by DemoorBug** [comment]
This setting is not valid
`export MKL_DEBUG_CPU_TYPE=5`

**Comment by NyaomiDEV** [comment]
Absolutely no support is given to people using this project.
This is a weekend project I made, and I expect NO issue tickets. By using such experimental stuff, you are on your own.
